[2024-04-20T16:15:01.860+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-04-20T13:15:00+00:00 [queued]>
[2024-04-20T16:15:01.888+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-04-20T13:15:00+00:00 [queued]>
[2024-04-20T16:15:01.889+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-20T16:15:01.945+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-04-20 13:15:00+00:00
[2024-04-20T16:15:01.958+0000] {standard_task_runner.py:60} INFO - Started process 1303246 to run task
[2024-04-20T16:15:01.971+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_up_gcs', 'get_data_api', 'scheduled__2024-04-20T13:15:00+00:00', '--job-id', '1051', '--raw', '--subdir', 'DAGS_FOLDER/test_get_up_gcs.py', '--cfg-path', '/tmp/tmp3i2sp8ig']
[2024-04-20T16:15:01.979+0000] {standard_task_runner.py:88} INFO - Job 1051: Subtask get_data_api
[2024-04-20T16:15:02.145+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-04-20T13:15:00+00:00 [running]> on host c5a6ac367c49
[2024-04-20T16:15:02.447+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_up_gcs' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T13:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-20T13:15:00+00:00'
[2024-04-20T16:15:12.577+0000] {test_get_up_gcs.py:60} INFO - JSON data saved to /opt/***/dags/data_2024_04_20_2300.json
[2024-04-20T16:15:12.578+0000] {test_get_up_gcs.py:64} INFO - local file path : /opt/***/dags/data_2024_04_20_2300.json
[2024-04-20T16:15:12.579+0000] {test_get_up_gcs.py:68} INFO - bucket name : ds525-capstone-test-49
[2024-04-20T16:15:12.579+0000] {test_get_up_gcs.py:71} INFO - dst : data/data_2024_04_20_2300.json
[2024-04-20T16:15:12.604+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-20T16:15:12.615+0000] {base.py:83} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-20T16:15:13.576+0000] {gcs.py:557} INFO - File /opt/***/dags/data_2024_04_20_2300.json uploaded to data/data_2024_04_20_2300.json in ds525-capstone-test-49 bucket
[2024-04-20T16:15:13.593+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-20T16:15:13.649+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_get_up_gcs, task_id=get_data_api, execution_date=20240420T131500, start_date=20240420T161501, end_date=20240420T161513
[2024-04-20T16:15:13.705+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-20T16:15:13.746+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
