[2024-03-25T17:39:24.046+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-03-25T07:15:00+00:00 [queued]>
[2024-03-25T17:39:24.134+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-03-25T07:15:00+00:00 [queued]>
[2024-03-25T17:39:24.136+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-25T17:39:24.219+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-03-25 07:15:00+00:00
[2024-03-25T17:39:24.241+0000] {standard_task_runner.py:60} INFO - Started process 1515 to run task
[2024-03-25T17:39:24.264+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_up_gcs', 'get_data_api', 'scheduled__2024-03-25T07:15:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/test_get_up_gcs.py', '--cfg-path', '/tmp/tmpuooui6oh']
[2024-03-25T17:39:24.271+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask get_data_api
[2024-03-25T17:39:24.619+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-03-25T07:15:00+00:00 [running]> on host c5a6ac367c49
[2024-03-25T17:39:25.209+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_up_gcs' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T07:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T07:15:00+00:00'
[2024-03-25T17:39:30.601+0000] {test_get_up_gcs.py:50} INFO - JSON data saved to /opt/***/dags/data_get.json
[2024-03-25T17:39:30.608+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-25T17:39:30.638+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_get_up_gcs, task_id=get_data_api, execution_date=20240325T071500, start_date=20240325T173924, end_date=20240325T173930
[2024-03-25T17:39:30.741+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-25T17:39:30.802+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-25T19:37:56.436+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-03-25T07:15:00+00:00 [queued]>
[2024-03-25T19:37:56.536+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-03-25T07:15:00+00:00 [queued]>
[2024-03-25T19:37:56.537+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-25T19:37:56.649+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-03-25 07:15:00+00:00
[2024-03-25T19:37:56.675+0000] {standard_task_runner.py:60} INFO - Started process 5443 to run task
[2024-03-25T19:37:56.702+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_up_gcs', 'get_data_api', 'scheduled__2024-03-25T07:15:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/test_get_up_gcs.py', '--cfg-path', '/tmp/tmpn166zlb9']
[2024-03-25T19:37:56.714+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask get_data_api
[2024-03-25T19:37:57.193+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-03-25T07:15:00+00:00 [running]> on host c5a6ac367c49
[2024-03-25T19:38:00.128+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_up_gcs' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T07:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T07:15:00+00:00'
[2024-03-25T19:38:24.447+0000] {test_get_up_gcs.py:60} INFO - JSON data saved to /opt/***/dags/data_2024_03_26_0200.json
[2024-03-25T19:38:24.449+0000] {test_get_up_gcs.py:64} INFO - local file path : /opt/***/dags/data_2024_03_26_0200.json
[2024-03-25T19:38:24.451+0000] {test_get_up_gcs.py:68} INFO - bucket name : ds525-capstone-test-49
[2024-03-25T19:38:24.452+0000] {test_get_up_gcs.py:71} INFO - dst : data/data_2024_03_26_0200.json
[2024-03-25T19:38:24.482+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-25T19:38:24.494+0000] {base.py:83} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-03-25T19:38:25.571+0000] {gcs.py:557} INFO - File /opt/***/dags/data_2024_03_26_0200.json uploaded to data/data_2024_03_26_0200.json in ds525-capstone-test-49 bucket
[2024-03-25T19:38:25.574+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_get_up_gcs.py", line 85, in _get_data_api
    os.remove(local_file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data_2024_03_26_0200.json'
[2024-03-25T19:38:25.600+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=test_get_up_gcs, task_id=get_data_api, execution_date=20240325T071500, start_date=20240325T193756, end_date=20240325T193825
[2024-03-25T19:38:25.639+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 61 for task get_data_api ([Errno 2] No such file or directory: '/opt/airflow/dags/data_2024_03_26_0200.json'; 5443)
[2024-03-25T19:38:25.702+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T19:38:25.782+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
