[2024-05-03T01:15:01.868+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-05-02T22:15:00+00:00 [queued]>
[2024-05-03T01:15:01.899+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-05-02T22:15:00+00:00 [queued]>
[2024-05-03T01:15:01.900+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-03T01:15:01.951+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-05-02 22:15:00+00:00
[2024-05-03T01:15:01.967+0000] {standard_task_runner.py:60} INFO - Started process 125720 to run task
[2024-05-03T01:15:01.981+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_up_gcs', 'get_data_api', 'scheduled__2024-05-02T22:15:00+00:00', '--job-id', '2228', '--raw', '--subdir', 'DAGS_FOLDER/test_get_up_gcs.py', '--cfg-path', '/tmp/tmpcfwfddls']
[2024-05-03T01:15:01.989+0000] {standard_task_runner.py:88} INFO - Job 2228: Subtask get_data_api
[2024-05-03T01:15:02.226+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-05-02T22:15:00+00:00 [running]> on host 5373b942cc14
[2024-05-03T01:15:02.572+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_up_gcs' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T22:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T22:15:00+00:00'
[2024-05-03T01:15:23.574+0000] {test_get_up_gcs.py:60} INFO - JSON data saved to /opt/***/dags/data_2024_05_03_0800.json
[2024-05-03T01:15:23.574+0000] {test_get_up_gcs.py:64} INFO - local file path : /opt/***/dags/data_2024_05_03_0800.json
[2024-05-03T01:15:23.575+0000] {test_get_up_gcs.py:68} INFO - bucket name : ds525-capstone-test-49
[2024-05-03T01:15:23.576+0000] {test_get_up_gcs.py:71} INFO - dst : data/data_2024_05_03_0800.json
[2024-05-03T01:15:23.600+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-03T01:15:23.611+0000] {base.py:83} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-03T01:15:24.571+0000] {gcs.py:557} INFO - File /opt/***/dags/data_2024_05_03_0800.json uploaded to data/data_2024_05_03_0800.json in ds525-capstone-test-49 bucket
[2024-05-03T01:15:24.578+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-05-03T01:15:24.611+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_get_up_gcs, task_id=get_data_api, execution_date=20240502T221500, start_date=20240503T011501, end_date=20240503T011524
[2024-05-03T01:15:24.697+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-03T01:15:24.738+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
