[2024-04-14T13:15:02.306+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-04-14T10:15:00+00:00 [queued]>
[2024-04-14T13:15:02.334+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-04-14T10:15:00+00:00 [queued]>
[2024-04-14T13:15:02.335+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-14T13:15:02.382+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-04-14 10:15:00+00:00
[2024-04-14T13:15:02.398+0000] {standard_task_runner.py:60} INFO - Started process 853331 to run task
[2024-04-14T13:15:02.412+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_up_gcs', 'get_data_api', 'scheduled__2024-04-14T10:15:00+00:00', '--job-id', '812', '--raw', '--subdir', 'DAGS_FOLDER/test_get_up_gcs.py', '--cfg-path', '/tmp/tmpzl501gzq']
[2024-04-14T13:15:02.420+0000] {standard_task_runner.py:88} INFO - Job 812: Subtask get_data_api
[2024-04-14T13:15:02.587+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_up_gcs.get_data_api scheduled__2024-04-14T10:15:00+00:00 [running]> on host c5a6ac367c49
[2024-04-14T13:15:02.910+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_up_gcs' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T10:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T10:15:00+00:00'
[2024-04-14T13:15:03.923+0000] {test_get_up_gcs.py:60} INFO - JSON data saved to /opt/***/dags/data_2024_04_14_2000.json
[2024-04-14T13:15:03.924+0000] {test_get_up_gcs.py:64} INFO - local file path : /opt/***/dags/data_2024_04_14_2000.json
[2024-04-14T13:15:03.925+0000] {test_get_up_gcs.py:68} INFO - bucket name : ds525-capstone-test-49
[2024-04-14T13:15:03.926+0000] {test_get_up_gcs.py:71} INFO - dst : data/data_2024_04_14_2000.json
[2024-04-14T13:15:03.950+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-14T13:15:03.963+0000] {base.py:83} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-14T13:15:04.930+0000] {gcs.py:557} INFO - File /opt/***/dags/data_2024_04_14_2000.json uploaded to data/data_2024_04_14_2000.json in ds525-capstone-test-49 bucket
[2024-04-14T13:15:04.937+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-14T13:15:04.969+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_get_up_gcs, task_id=get_data_api, execution_date=20240414T101500, start_date=20240414T131502, end_date=20240414T131504
[2024-04-14T13:15:05.038+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-14T13:15:05.083+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
